#!/usr/bin/env node

const { execSync } = require("child_process");
const { version } = require("./package.json");

try {
    execSync("rm -r binaries/");
} catch (err) {
    // ignore
}

execSync("mkdir -p binaries");
execSync("yarn pkg -t node10-linux-x86,node10-linux-x64,node10-macos-x64,node10-windows-x86,node10-windows-x64 --out-path binaries/ package.json");


const files = [
    "codechain-keystore-cli-linux-x64",
    "codechain-keystore-cli-linux-x86",
    "codechain-keystore-cli-macos-x64",
    "codechain-keystore-cli-win-x64.exe",
    "codechain-keystore-cli-win-x86.exe"
];

process.chdir("binaries");
for (const file of files) {
    const distFile = getDistFile(file);
    execSync(`mv ${file} ${distFile}`);
    const dir = removeExe(file);
    execSync(`mkdir -p ${dir}`);
    execSync(`mv ${distFile} ${dir}/`);

    execSync(`zip -r ${dir}-${version}.zip ${dir}`);
}

/**
 * @param {string} fileName
 */
function removeExe(fileName) {
    if (fileName.indexOf("exe") !== -1) {
        return fileName.slice(0, fileName.length - 4);
    } else {
        return fileName;
    }
}

function getDistFile(fileName) {
    if (fileName.indexOf("exe") !== -1) {
        return "cckey.exe";
    } else {
        return "cckey";
    }
}
